/*
 * SourceApi
 *
 * A Web API for controlling a source.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/ZeraGmbH/rest-go-playground/go"
)

func main() {
	log.Printf("Server started")

	VeinAPIService := openapi.NewVeinAPIService()
	VeinAPIController := openapi.NewVeinAPIController(VeinAPIService)

	router := openapi.NewRouter(VeinAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
