/*
 * SourceApi
 *
 * A Web API for controlling a source.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	VeinApiService := openapi.NewVeinApiService()
	VeinApiController := openapi.NewVeinApiController(VeinApiService)

	router := openapi.NewRouter(VeinApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
