/*
 * SourceApi
 *
 * A Web API for controlling a source.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
)



// VeinAPIRouter defines the required methods for binding the api requests to a responses for the VeinAPI
// The VeinAPIRouter implementation should parse necessary information from the http request,
// pass the data to a VeinAPIServicer to perform the required actions, then write the service results to the http response.
type VeinAPIRouter interface { 
	ApiV1VeinGetInfoPost(http.ResponseWriter, *http.Request)
	ApiV1VeinSetInfoPost(http.ResponseWriter, *http.Request)
}


// VeinAPIServicer defines the api actions for the VeinAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type VeinAPIServicer interface { 
	ApiV1VeinGetInfoPost(context.Context, VeinGet) (ImplResponse, error)
	ApiV1VeinSetInfoPost(context.Context, VeinSet) (ImplResponse, error)
}
