/*
 * SourceApi
 *
 * A Web API for controlling a source.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type VeinGetResponse struct {

	// The desired return information formated as json
	ReturnInformation string `json:"ReturnInformation,omitempty"`

	// The original data Type
	Type string `json:"type,omitempty"`

	Status *int32 `json:"status,omitempty"`
}

// AssertVeinGetResponseRequired checks if the required fields are not zero-ed
func AssertVeinGetResponseRequired(obj VeinGetResponse) error {
	return nil
}

// AssertVeinGetResponseConstraints checks if the values respects the defined constraints
func AssertVeinGetResponseConstraints(obj VeinGetResponse) error {
	return nil
}
