/*
 * SourceApi
 *
 * A Web API for controlling a source.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type VeinSet struct {

	// The component ID of the desired information
	EntityID int32 `json:"EntityID,omitempty"`

	// The component name of the desired information
	ComponentName string `json:"componentName,omitempty"`

	// However we want to handle the setter field
	MiscFieldForInfo string `json:"MiscFieldForInfo,omitempty"`
}

// AssertVeinSetRequired checks if the required fields are not zero-ed
func AssertVeinSetRequired(obj VeinSet) error {
	return nil
}

// AssertRecurseVeinSetRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of VeinSet (e.g. [][]VeinSet), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseVeinSetRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aVeinSet, ok := obj.(VeinSet)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertVeinSetRequired(aVeinSet)
	})
}
