/*
 * SourceApi
 *
 * A Web API for controlling a source.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type VeinGet struct {

	// The component ID of the desired information
	EntityID int32 `json:"EntityID,omitempty"`

	// The component name of the desired information
	ComponentName string `json:"componentName,omitempty"`
}

// AssertVeinGetRequired checks if the required fields are not zero-ed
func AssertVeinGetRequired(obj VeinGet) error {
	return nil
}

// AssertVeinGetConstraints checks if the values respects the defined constraints
func AssertVeinGetConstraints(obj VeinGet) error {
	return nil
}
