/*
 * SourceApi
 *
 * A Web API for controlling a source.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type VeinSet struct {

	// The component ID of the desired information
	EntityID int32 `json:"EntityID,omitempty"`

	// The component name of the desired information
	ComponentName string `json:"componentName,omitempty"`

	// newValue to set to component
	NewValue string `json:"newValue,omitempty"`
}

// AssertVeinSetRequired checks if the required fields are not zero-ed
func AssertVeinSetRequired(obj VeinSet) error {
	return nil
}

// AssertVeinSetConstraints checks if the values respects the defined constraints
func AssertVeinSetConstraints(obj VeinSet) error {
	return nil
}
